# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZ7m5mKNXoHfwlb6p9_9lgHGT_WVJyfi
"""

import pandas as pd
df = pd.read_csv("/content/Call_Data_20260329.csv")

df['Event Group'].value_counts(dropna=False)

def group_event_group(x):
    if x in [
        "Assaults", "Domestic Disturbance/Violence", "Robbery", "Rape",
        "Homicide", "Kidnap", "Threats/Harassment (No Bias)",
        "Human Trafficking", "Sex Offenses (Non-Rape)",
        "Child (Abandoned, Abused, or Neglected)"
    ]:
        return "Crime Against Persons"

    if x in [
        "Burglary", "Theft", "Property Destruction (Damage)", "Automobiles",
        "Prowler", "Mischief & Nuisance", "Fraud & Forgery",
        "Arson, Bombs, Explosion", "Vice",
        "Misc. Misdemeanors & Violations"
    ]:
        return "Crime Against Property"

    if x in [
        "Crisis Complaint", "Casualty (Non-Traffic. Non-Criminal, including Man Down, Injured & Sick Person, DOA)",
        "Intoxication & Liquor Violations", "Detox", "Swatting"
    ]:
        return "Behavioral Health & Crisis"

    if x in [
        "Disturbance", "Suspicious Circumstances", "Public Gatherings",
        "Hazards", "Shots", "Animal Complaint"
    ]:
        return "Public Disturbance & Disorder"

    if x in ["Traffic", "Harbor (Water)", "Escape/Eluding Police"]:
        return "Traffic & Transportation"

    if x in [
        "Premise Checks", "Directed Patrol", "Assigned Duty", "Administrative",
        "Follow-ups", "Assist the Officer", "Warrant Services/Order",
        "Assist Other Agency", "Info & Radio Broadcast"
    ]:
        return "Administrative & Officer-Initiated"

    if x in ["Assist Public", "Person Missing/Found", "Property"]:
        return "Welfare & Assist Public"

    return "Other / Unknown"

df["event_group_bucket"] = df["Event Group"].apply(group_event_group)

print(df['Dispatch Beat'].isna().sum())
print(df['Dispatch Precinct'].isna().sum())
col = 'First SPD Call Sign Dispatch Time (s)'
col2 = 'First SPD Call Sign Response Time (s)'
df[col2] = (
    df[col2]
    .str.replace(',', '', regex=False)   # remove commas
    .astype(float)                       # convert to numeric
)
col = 'First SPD Call Sign Dispatch Delay Time (s)'
df[col] = (
    df[col]
    .str.replace(',', '', regex=False)   # remove commas
    .astype(float)                       # convert to numeric
)

df[col].head(20).tolist()

df[col].describe(percentiles=[0.5, 0.9, 0.95, 0.99])
df[col2].describe(percentiles=[0.5, 0.9, 0.95, 0.99])

df['dispatch_delay_capped'] = df['First SPD Call Sign Dispatch Delay Time (s)'].clip(upper=7200)
df['dispatch_delay_extreme'] = df['First SPD Call Sign Dispatch Delay Time (s)'] > 7200
df['response_capped'] = df['First SPD Call Sign Response Time (s)'].clip(upper=7200)
df['response_extreme'] = df['First SPD Call Sign Response Time (s)'] > 7200
df['response_extreme'] = df['First SPD Call Sign Response Time (s)'] > 7200

df.to_csv("cleaned_calls.csv", index=False)
from google.colab import files
files.download("cleaned_calls.csv")